//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_Mehmet_Sirket_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun_Tablosu
    {
       public int urun_id { get; set; }
        public string urun_kodu { get; set; }
        public string urun_ad { get; set; }
        public int stok_mik { get; set; }
        public int fiyat { get; set; }
    }
}
